import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.raw(`CREATE TABLE [dbo].[shipper_user_1] (
  [statusrelasi] varchar(200) NULL,
  [relasi_id] varchar(200) NULL,
  [nama] nvarchar(255) NULL,
  [keterangan] nvarchar(MAX) NULL,
  [contactperson] nvarchar(255) NULL,
  [alamat] nvarchar(MAX) NULL,
  [coa] nvarchar(100) NULL,
  [coapiutang] nvarchar(100) NULL,
  [coahutang] nvarchar(100) NULL,
  [kota] nvarchar(100) NULL,
  [kodepos] nvarchar(20) NULL,
  [telp] nvarchar(50) NULL,
  [email] nvarchar(255) NULL,
  [fax] nvarchar(50) NULL,
  [web] nvarchar(255) NULL,
  [creditlimit] decimal(18,2) NULL,
  [creditterm] int NULL,
  [credittermplus] int NULL,
  [npwp] nvarchar(50) NULL,
  [coagiro] nvarchar(100) NULL,
  [ppn] decimal(5,2) NULL,
  [titipke] nvarchar(255) NULL,
  [ppnbatalmuat] decimal(5,2) NULL,
  [grup] nvarchar(100) NULL,
  [formatdeliveryreport] int NULL,
  [comodity] nvarchar(255) NULL,
  [namashippercetak] nvarchar(255) NULL,
  [formatcetak] nvarchar(50) NULL,
  [marketing_id] varchar(200) NULL,
  [blok] nvarchar(50) NULL,
  [nomor] nvarchar(50) NULL,
  [rt] nvarchar(10) NULL,
  [rw] nvarchar(10) NULL,
  [kelurahan] nvarchar(100) NULL,
  [kabupaten] nvarchar(100) NULL,
  [kecamatan] nvarchar(100) NULL,
  [propinsi] nvarchar(100) NULL,
  [isdpp10psn] bit NULL,
  [usertracing] nvarchar(100) NULL,
  [passwordtracing] nvarchar(100) NULL,
  [kodeprospek] nvarchar(50) NULL,
  [namashipperprospek] nvarchar(255) NULL,
  [emaildelay] nvarchar(255) NULL,
  [keterangan1barisinvoice] nvarchar(MAX) NULL,
  [nik] nvarchar(50) NULL,
  [namaparaf] nvarchar(255) NULL,
  [saldopiutang] decimal(18,2) NULL,
  [keteranganshipperjobminus] nvarchar(MAX) NULL,
  [tglemailshipperjobminus] nvarchar(20) NULL,
  [tgllahir] nvarchar(20) NULL,
  [idshipperasal] int NULL,
  [initial] nvarchar(10) NULL,
  [tipe] nvarchar(50) NULL,
  [idtipe] int NULL,
  [idinitial] int NULL,
  [nshipperprospek] nvarchar(255) NULL,
  [parentshipper_id] varchar(200) NULL,
  [npwpnik] nvarchar(50) NULL,
  [nitku] nvarchar(50) NULL,
  [kodepajak] nvarchar(50) NULL,
  [statusaktif] varchar(200) NULL,
  [info] nvarchar(MAX) NULL,
  [modifiedby] nvarchar(100) NOT NULL DEFAULT (''),
  [created_at] nvarchar(20) NOT NULL DEFAULT (CONVERT([nvarchar](30),getdate(),(126))),
  [updated_at] nvarchar(20) NOT NULL DEFAULT (CONVERT([nvarchar](30),getdate(),(126))),
  [id] varchar(200) NOT NULL,
  CONSTRAINT [PK_shipper_user_1] PRIMARY KEY ([id])
);`);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.raw('DROP TABLE IF EXISTS [dbo].[shipper_user_1];');
}
