import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.raw(`CREATE TABLE [dbo].[shipper] (
  [statusrelasi] varchar(200) NULL,
  [relasi_id] varchar(200) NULL,
  [nama] varchar(8000) NULL,
  [keterangan] varchar(8000) NULL,
  [contactperson] varchar(100) NULL,
  [alamat] varchar(250) NULL,
  [coa] nvarchar(100) NULL,
  [coapiutang] nvarchar(100) NULL,
  [coahutang] nvarchar(100) NULL,
  [kota] varchar(50) NULL,
  [kodepos] varchar(10) NULL,
  [telp] varchar(30) NULL,
  [email] varchar(1000) NULL,
  [fax] varchar(30) NULL,
  [web] varchar(30) NULL,
  [creditlimit] money NULL,
  [creditterm] bigint NULL,
  [credittermplus] bigint NULL,
  [npwp] varchar(30) NULL,
  [coagiro] nvarchar(100) NULL,
  [ppn] money NULL,
  [titipke] varchar(30) NULL,
  [ppnbatalmuat] money NULL,
  [grup] varchar(100) NULL,
  [formatdeliveryreport] bigint NULL,
  [comodity] varchar(100) NULL,
  [namashippercetak] varchar(100) NULL,
  [formatcetak] bigint NULL,
  [marketing_id] varchar(200) NULL,
  [blok] varchar(100) NULL,
  [nomor] varchar(100) NULL,
  [rt] varchar(100) NULL,
  [rw] varchar(100) NULL,
  [kelurahan] varchar(100) NULL,
  [kabupaten] varchar(100) NULL,
  [kecamatan] varchar(100) NULL,
  [propinsi] varchar(100) NULL,
  [isdpp10psn] money NULL,
  [usertracing] varchar(50) NULL,
  [passwordtracing] varchar(50) NULL,
  [kodeprospek] varchar(50) NULL,
  [namashipperprospek] varchar(200) NULL,
  [emaildelay] varchar(1000) NULL,
  [keterangan1barisinvoice] varchar(100) NULL,
  [nik] varchar(30) NULL,
  [namaparaf] varchar(100) NULL,
  [saldopiutang] money NULL,
  [keteranganshipperjobminus] varchar(500) NULL,
  [tglemailshipperjobminus] datetime NULL,
  [tgllahir] datetime NULL,
  [idshipperasal] bigint NULL,
  [initial] varchar(100) NULL,
  [tipe] varchar(100) NULL,
  [idtipe] bigint NULL,
  [idinitial] bigint NULL,
  [nshipperprospek] varchar(500) NULL,
  [parentshipper_id] varchar(200) NULL,
  [npwpnik] varchar(16) NULL,
  [nitku] varchar(22) NULL,
  [kodepajak] varchar(10) NULL,
  [statusaktif] varchar(200) NULL,
  [info] varchar(4000) NULL,
  [modifiedby] varchar(200) NOT NULL DEFAULT (''),
  [created_at] datetime NOT NULL DEFAULT (getdate()),
  [updated_at] datetime NOT NULL DEFAULT (getdate()),
  [id] varchar(200) NOT NULL,
  CONSTRAINT [PK_shipper] PRIMARY KEY ([id])
);`);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.raw('DROP TABLE IF EXISTS [dbo].[shipper];');
}
